### PR TITLE
fixed search token logic bug ..

### PR DESCRIPTION
**Pull request by soichih**
and allowing various items in the poster entry to be clicked to fed to the search criteria #119
made the pdf to be more clearly understood as opening PDF #120

### CODE REVIEW

**Comment by yarikoptic** [comment]
woohoo -- awesome!   I am ok to have it merged, but here is some notes (besides the occlusion mentioned in #120 )

- Could there be a button in "Search" box - "Clear filters"?  that would simplify getting back to original state
- probably hard -- when I change selection while being on the poster somewhere deep down, the whole listing changes and I end up above some other poster.  I wonder if there is some quick way ("go to #segment" or alike) to also scroll back to that poster in the updated view?

**Comment by yarikoptic** [comment]
actually "the hard one" -- I think it already does that, doesn't it? ;)

**Comment by yarikoptic** [comment]
now I am pretty sure it does!  I just didn't pay attention to the numbers originally -- awesome!  Lets proceed forward -- click Merge @soichih if you are done with it ;-)

**Comment by soichih** [comment]
I've addressed #120. Pushing the merge button now!!

**Comment by yarikoptic** [comment]
awesome!

**Pull request merged**
