### PR TITLE
Minor updates to Room.vue 

### PR DESCRIPTION
**Pull request by soichih**
This is *no longer* for #170 

This is a minor cosmetic update to prevent the *NOTE* tag from floating in the middle of the screen while etherpad is loaded.
I've also dropped the protocol as it is *unnecessary*, and also it could cause protocol mismatch if the page is served via http rather than https.

### CODE REVIEW

**Review by yarikoptic — CHANGES_REQUESTED** [review]
Also don't changes to .Vue require rebuild of produced js?

IMHO best to split this PR in two.

**Comment by soichih** [comment]
Yes, I should make another PR. I will submit another PR for the README shortly

**Comment by yarikoptic** [comment]
Cool. Don't we need js/css rebuild to be included ATM to take effect of the changes?

**Comment by soichih** [comment]
I just pushed the ./static update.

**Comment by yarikoptic** [comment]
Coolio, thanks! Let's see it in action ;-)

**Pull request merged**
