### PR TITLE
Initial commit of vue framework

### PR DESCRIPTION
**Pull request by emdupre**
This is a huge, not yet functioning PR :disappointed: 

The idea is that we could convert the existing content to use a Vue framework, since it would make it easier to restructure / integrate new JavaScript.

I'm only posting it now since I need to take a few hours to do other things, and I'm happy to have anyone else join in !

### CODE REVIEW

**Comment by soichih** [comment]
@emdupre I only see the vue-cli's boiler plate code, but do you have things under ./src that you haven't committed? By the way, you should add node_modules to .gitignore (and commit `package.json` and `package-lock.json` so people can reproduce the node_modules). This will be awesome!

**Comment by emdupre** [comment]
Thanks, @soichih !! I set this all up in another folder and clearly didn't move the content properly.

I've removed the node_modules from tracking. I do have a `package.json` included, and under `src` it should include a routing infrastructure as well as some of the content from the initial site (like the DataLad logo). What needs to happen next, I think, is to either import main.js or transfer that functionality directly into the Home.vue component !

**Comment by yarikoptic** [comment]
Please make it coinstable with current one, ie make `index_vue.html` so we could merge, direct to it, test drive, before making it default one

**Comment by emdupre** [comment]
@yarikoptic I think that the best way to do that is if you could create a branch that this could be merged into, and then we could build the netlify app from that branch ?

**Comment by yarikoptic** [comment]
I have pushed `vue` branch.  I still remain of the opinion that "coinstallability" would be a great feature to have to be able to switch between interfaces in case of detected problem.  Please keep that in mind

**Comment by yarikoptic** [comment]
Hey @all-contributors please add @emdupre for code ideas

**Comment by soichih** [comment]
I think I will have a few hours to work on the Vue based UI. @emdupre, please let me know if there is already some `./src` content that I should start with. I am thinking about creating a google image result page like UI that displays thumbnails of all posters.

**Comment by emdupre** [comment]
Thanks, @soichih !

There should be ./src content in [here](https://github.com/emdupre/ohbm2020-posters/tree/vuetify/src). I had started this since @rmarkello asked about making different tabs to show the content, so this has routing set up, at least. It would need to be merged to show up on the vue branch here, though !

**Comment by soichih** [comment]
Oh I see it! Awesome. I think we could host the vue branch co-existing with the gh-pages and exposed under a different index.html - so we can easily test between the current UI and the Vue UI.. I think @yarikoptic also wanted that as well.

**Comment by emdupre** [comment]
Yes, I agree that was the goal ! I think I just don't see how to do it. But if you have a structure in mind I'm happy to try it out !!

**Comment by emdupre** [comment]
Ah, so you compiled the site and then pushed ? I was trying to avoid that, but I think you're right that it makes more sense for now ! Thanks again !

**Comment by soichih** [comment]
Yes, we need to compile it for gh-pages. They don't do any kind of preprocessing/rendering for us.. it's pretty much just a static webserver, as far as I know?

**Comment by emdupre** [comment]
Yes, exactly -- I usually serve from Netlify for that reason ! But I wasn't
sure how to host from Netlify with two indexes, so this is probably the
better route 😸

Le dim. 28 juin 2020 20 h 57, Soichi Hayashi <notifications@github.com> a
écrit :

**Comment by soichih** [comment]
> Netlify
Oh~ that's cool. It runs `npm run build` for you wherever you push it? I
was playing around with Nuxt.js.. but I didn't quite get it. I was also
learning typescript and I kind of got frustrated by that.. not
nuxt.js's fault. I feel very out-of-date lately.

**Comment by emdupre** [comment]
> It runs `npm run build` for you wherever you push it? 

Yes, exactly ! So all the code is still hosted on GitHub but it's continuously deployed on Netlify. They even have a really nice GitHub integration where it will register as a status check on PRs as to whether the site built correctly, and of course a fun badge for the README :)

**Comment by emdupre** [comment]
>  I feel very out-of-date lately.

I'm still learning all of this, so I have no real benchmarks for what is and isn't common. But there are definitely a lot of moving pieces, and they all seem to be moving at different speeds ! But when the site looks (and works) well, I think that's all that matters. Thanks again for getting it up and running !!

**Comment by soichih** [comment]
@yarikoptic 

Currently, I am rebuilding the ./static content everytime I make a new PR. Ideally, we only need to do this once before we do a release (by running `npm run build`). You can still test the UI by running `npm run dev` without building. If you are ok, I will stop rebuilding it before making a new PR as I don't want to push the whole ./static content as part of git commit.. 

As @emdupre and I pointed out.. we *do* need to manually rebuild and push the static content to this git repo so that gh-pages can serve the static content.. unfortunately.

**Pull request closed without merging**
