### PR TITLE
convert github.com raw url to raw.githack.com url / adding etherpad on the right

### PR DESCRIPTION
**Pull request by soichih**
ref https://github.com/datalad-datasets/ohbm2020-posters/pull/143

This update converts github raw url (that doesn't set content-type) to raw.githack.com url so that user can open the pdf directly on the browser.

### CODE REVIEW

**Comment by soichih** [comment]
image

The etherpad tries to address these issues
REF https://github.com/datalad-datasets/ohbm2020-posters/issues/127
https://github.com/datalad-datasets/ohbm2020-posters/issues/157 (somewhat)

**Comment by yarikoptic** [comment]
could not test locally, even if I allow cookies for 127.0.0.1 chromium doesn't really record it and I come back to
```
An error occurred
Please press and hold Ctrl and press F5 to reload this page
If the problem persists please send this error message to your webmaster:

ErrorId: trC36oQ4gYH2Mk17yHq0
URL: https://etherpad.wikimedia.org/p/ohbm2020-3
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Uncaught TypeError: Cannot read property 'setStateIdle' of null in https://etherpad.wikimedia.org/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=2eb54623 at line 3
```
even going to localhost doesn't help... will deploy/test tomorrow.  If PDF was a separate PR - would have been easier to review/merge

**Comment by yarikoptic** [comment]
and going back to df7edb282a0e3364fa51e87e09a7136143731a87 before presumably etherpad addition - doesn't work

**Comment by soichih** [comment]
Does it work on my fork? https://soichi.us/ohbm2020-posters/#/room/3/ohbm2020-3

**Comment by yarikoptic** [comment]
Nope (although this time coming from phone not laptop) - similar cookie issue

**Comment by soichih** [comment]
I just tested with a few people and they all seemed to work.. on my fork. I
am wondering if the issue is caused by your browser / OS?

[image: image.png]

I did forget to hide the note for mobile.. so I will do that now.

**Comment by yarikoptic** [comment]
from your clone:
- worked in firefox
- in chromium (and I guess chome on android as I reported earlier), it works ONLY if either I 
  - disable "Block third-party cookies".   adding your website (soichi.us) to the list of allowed doesn't help
  - manually add `etherpad.wikimedia.org` to the list of allowed websites for the cookies

I wonder if there could be at least a message (e.g. instead of error msg) in such cases instructing user to do that (add etherpad.wikimedia.org or allow for third-party cookies).  I am not sure why chromium doesn't ask me explicitly for cookies from that website to be allowed or not.

**Comment by soichih** [comment]
Actually.. I was able to recreate this problem on *some* posters (happens on 1966 consistently).

It looks like etherpad is trying to send some warning message through "top" property. 

```
                r[t] = i(function() {
                    "setAuthorInfo" !== t || arguments[0] ? d[n + t].apply(this, arguments) : top.console.warn("setAuthorInfo AuthorId not set for some reason", arguments)
                })
```

I don't know 1) what `AuthorId` is, why it's not set and how to set it. 2) why this only happens on 1966, 3) if this is a bug with etherpad itself.. I don't think it should be accessing `window.top` to post messages like that.

**Comment by yarikoptic** [comment]
submit issue to etherpad and see what they say?

**Comment by soichih** [comment]
I've looked and it looks like they've already fixed it.

> https://github.com/ether/etherpad-lite/blob/c5584fb5b41a67704bcad4178a5420377b6988ab/src/static/js/ace2_inner.js#L344

Also, I just refreshed 1966 and now it's working again.. :( I am guessing wikimedia.org has some old code stuck in one of their servers, or CDN.. or something)

**Comment by yarikoptic** [comment]
FWIW, twitted:
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">An exciting new feature to the <a href="https://twitter.com/hashtag/GallOP?src=hash&amp;ref_src=twsrc%5Etfw">#GallOP</a> (our platform name now) got just added by the amazing <a href="https://twitter.com/soichih?ref_src=twsrc%5Etfw">@soichih</a> -- integration with <a href="https://twitter.com/EtherpadOrg?ref_src=twsrc%5Etfw">@EtherpadOrg</a>! &quot;Video chat&quot; has &quot;Notes&quot; on the right. Some rough corners might be yet to polish - please provide feedback! <a href="https://twitter.com/hashtag/OHBM2020Posters?src=hash&amp;ref_src=twsrc%5Etfw">#OHBM2020Posters</a> FOREVER! <a href="https://t.co/1iLAENlcLk">pic.twitter.com/1iLAENlcLk</a></p>&mdash; Yaroslav Halchenko (@yarikoptic) <a href="https://twitter.com/yarikoptic/status/1278716732543295489?ref_src=twsrc%5Etfw">July 2, 2020</a></blockquote>

**Pull request merged**
