### PR TITLE
Adds poster_downloads.csv with download links, titles, categories

### PR DESCRIPTION
**Pull request by rmarkello**
Not _exactly_ a poster update, but I scraped all the download links from the OHBM website along with the poster title and their primary category (if one was provided; otherwise it's just "undefined" cause I don't know javascript 🤷‍♂️ ).

I'm working on matching them up with the "originals" and can probably do a mass update of the posters-overrides.json if desired. Either way, figured I'd provide the CSV here as a reference in case anyone else wants to get in on it!

### CODE REVIEW

**Comment by effigies** [comment]
Can you re-scrape with Python? If so, we can update [make_page..py](https://github.com/datalad-datasets/ohbm2020-posters/blob/gh-pages/tools/make_page.py) to include this data in the `posters.json` by default.

**Comment by effigies** [comment]
This is awesome, btw.

**Comment by rmarkello** [comment]
Errrr, re-scraping with Python might be tough. You have to be signed into the conference platform to have access to the object with all the download info...

If it helps, here's how I made the array when logged into the platform (please ignore my hideous JS and the hack to get undefined to actually be a string):

```javascript
data = Array()
for (i=0; i < VEP.contents.contents.length; i++) {
  if (VEP.contents.contents[i].hasOwnProperty("fileType")) {
    if (VEP.contents.contents[i].fileType == "pdf") {
      content = [i, VEP.contents.contents[i].action.slice(9), VEP.contents.contents[i].title, VEP.contents.contents[i].folders[0]]
      for (v=0; v < content.length; v++) {
        if (typeof content[v] == 'undefined') {
          content[v] = "undefined"
        }
      }
      data.push(content)
    }
  }
}
```

and then I exported that to a CSV file with some functions from StackOverflow :joy:

I almost _never_ use Python for web stuff, so if you have a way to do that in Python then by all means!

**Comment by rmarkello** [comment]
Also the tricky thing about matching them up is that titles are different on the OHBM platform than in the abstract list because of character count differences when submitting versus uploading (100 chars versus 80 chars). I was just writing up a little script to add all the "exact" matches and then was going to try and match the others based on "closeness" 🤷‍♂️

**Comment by rmarkello** [comment]
(Realizing now that some of these are _definitely not_ abstracts but other random PDFs from sponsors and stuff 🤷‍♂️ that's probably what the 'category' column is good for weeding out :+1: I'll check and see if there's another way to disambiguate on the OHBM platform)

**Comment by yarikoptic** [comment]
ha ha, **well done** @rmarkello !  Although it would be nice to have a script, I think it is ok for this occasion to not bother.
And also imho it should sit outside of posters.json and `make_page.py` should just read it and embed prior applying overrides.
There is a concern though -- whenever with PRs users implicitly announce that those URLs lead to the PDFs they are willing to have publicly accessed, populating **all** might violate expectations of some OHBM attendees about their materials not being available publicly... Or was there some statement during abstract submission that posters might be made available publicly?  We could also download all and then see which have license stated in the metadata, but that is really unlikely.

**Comment by rmarkello** [comment]
Ah, **very** important point @yarikoptic ! (Now I'm disappointed in myself for not having thought of that in the first place 🤦‍♂️)

I don't believe there was any statement of public availability during upload, but I agree that submitting a PR acts as a sort of implicit consent for that. I'm open to suggestions on where to go from here (including, if you think, deleting this file + closing the PR).

**Comment by yarikoptic** [comment]
well,, I slurped that file already and running `datalad addurls` on it (locally) so that
- we have an archive/backup
- I could check metadata if at least some have some license statement in them

I have just emailed Mike from OHBM with the question where I did state (very briefly) a possible concern.

**Comment by yarikoptic** [comment]
> and then I exported that to a CSV file with some functions from StackOverflow 
> 
> I almost _never_ use Python for web stuff, so if you have a way to do that in Python then by all means!

I would have appreciated some "brainhack tutorial" on how to do such scraping ;-) (I mean about what you have done, not about Python ways)

**Comment by rmarkello** [comment]
Any thoughts on ways to match these up to posters shared in the #OHBM2020Posters hashtag as a form of consent for public availability? :grin:

And re scraping: it...was not pretty. It involved lots of clicking around aimlessly through the platform. I'm sure it's something Anisha could have gotten done in a heartbeat, though 💪

**Comment by yarikoptic** [comment]
ATM I have no good ideas which would provide some kind of "bread crumbs" trail to ensure that it was authors who permitted linking and which would not require significant effort. Some automation is needed

**Comment by yarikoptic** [comment]
Ok, to my question:

Ok.  If we do get a full list of URLs, would it be ok if we make them publicly available? (URLs, not PDFs)

PS The question sounds simple but it is not ;)  Although PDFs are available from URLs without any authentication, they are otherwise not public.

On Wed, 24 Jun 2020, Mike - OHBM wrote:

Yep that would be fine!

**Comment by yarikoptic** [comment]
So I will take it as a green light! We just need to match titles. I think we could use python standard library for that, like we do for unrecognized commands in a number of tools to suggest: difflib see eg https://github.com/datalad/datalad/blob/38af32be0072dabff8d224ca16a3ab3e1cd7aed2/datalad/utils.py#L2379

Just compile a table for matches with first column the title from your table, next one the matched, next matched Id. Should be easy to quickly do visual pass to possibly identify needed to be fixed up or removed

**Comment by rmarkello** [comment]
I didn't know `difflib` was a thing—that's incredible! Anyway, I added a new CSV, as requested, with the script used to generate the matches if tweaking is desired (sorry, I used `pandas` 'cause I'm lazy).

I didn't do a _ton_ of visual inspection cause there's ~2000, but made a few manual edits (DataLad handbook didn't match, by default!).

**Comment by yarikoptic** [comment]
awesome!  Now just please just tune up that tools/make_page.py to use mapping and the original csv for urls to produce adjusted posters.json.  I will in the morning make a pass over matches (or may be @effigies would beat me to it) with a fresh eye so we do not miss something cruel and we proceed to get the ultimate posters.json!  Thank you again @rmarkello for making it happen!

**Comment by rmarkello** [comment]
Let me know if this works! I'm happy to drop the CSV files to keep the repo trim, but will leave them here until you say otherwise. In the `poster_downloads_matches.csv` I _only_ kept those files for which a putative match was found. That obviously leaves some posters out, but it managed to match >1400 pdfs so I'll take that as a win!

**Comment by yarikoptic** [comment]
Csv files are peanuts in size, don't worry about those

**Comment by yarikoptic** [comment]
@rmarkello ! On behalf of the OHBM folks thank you again for making this happen!
I have merge this branch into gh-pages (but without last commit to avoid conflicts) and pushed now -- it is deployed!  
I did eye ball matches and was amazed on how some were determined by difflib or you where titles didn't match exactly -- well done both of you ;)  didn't spot any problem. If anything -- people could report issues

**Comment by rmarkello** [comment]
Woohoo ! 🙌  Thanks so much for setting this all up!

**Pull request closed without merging**
