### PR TITLE
array handling for institution field on poster.json / added clear filter button for search box

### LINKED ISSUE #125: Add "Clear filters" to search "box" (not edit box, although could be there I guess)
Follow up to #121

### PR DESCRIPTION
**Pull request by soichih**
This should allow https://github.com/datalad-datasets/ohbm2020-posters/pull/126 to be merged

edit: closes #125

### CODE REVIEW

**Comment by soichih** [comment]
Also handles https://github.com/datalad-datasets/ohbm2020-posters/issues/125

**Comment by yarikoptic** [comment]
clear works awesome!  I will merge #126 locally to see how that would look and if all good merge both...

**Comment by yarikoptic** [comment]
hm, I am no longer sure the overloads are picked up on the client side any longer!?  I merged but no changes appear.

**Comment by yarikoptic** [comment]
ok - seems to be picked up in _orig UI but not in the new Vue.  Something to be fixed up before merging #126 I guess.  This one seems to be safe to go ;)

**Pull request merged**
