### PR TITLE
fix pdf path to poster #1860

### PR DESCRIPTION
**Pull request by katjaq**

### CODE REVIEW

**Comment by yarikoptic** [comment]
note that it would not fixup previews automagically.  for now it was a manual pass by @soichih , but I hope that is ok.

**Comment by katjaq** [comment]
ahhh, ok ! Sorry, just saw your note here. Hmm, mouffmouff. Next time then :) 
Or maybe we can also PR to his implementation? 😇

**Comment by yarikoptic** [comment]
@soichih -- is it easy to update the previews?
And I now finally will get into placing PDFs under git-annex control here -- might simplify it in the future!

**Comment by soichih** [comment]
I just re-ran the thumbnail script. @katjaq 's poster was actually stuck because my pdf download script didn't work and it was failing to convert to jpg. I've removed the broken .pdf on my cache and now I was able to generate it. About a few dozen new thumbnails were added.

**Comment by katjaq** [comment]
you guys are roooockstaaaars!! <3 <3 🚀 🎸 🚀 🎸 🚀 🎸 🚀 🎸  Thanks so much! And I guess I am speaking for all the dozen new happy people now :D

**Pull request merged**
