### PR TITLE
Handling connection from outside our Apps, and handling mobile phone interface

### LINKED ISSUE #153: Some wrong attendance counts might be from mobile
I think I have tried to show from the phone and it incremented but didn't decrement since I think I didn't actually start app

### PR DESCRIPTION
**Pull request by soichih**
Fixes #153 - by reporting the real participant counts from jitsi API. As long as there is at least 1 user joining from our site, the count will be *eventually consistent* even if someone is not connected through our site directly.

I also made various updates to make the UI a bit more Vue-like - to make it easier to maintain (for me.. at least).

### CODE REVIEW

**Comment by soichih** [comment]
Also fixed the issue where (non-0 people filter) is not applied when online count changes between 0 and non-0

**Comment by yarikoptic** [comment]
cool, let's see it in the battle field! ;-)

**Comment by yarikoptic** [comment]
Attn @socihih -- I guess this totally broke it

```
datalad-datasets.github.io/:1 A cookie associated with a cross-site resource at http://jit.si/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
app.f26ecf43857f2674339ad51c6079b894.css:1 Failed to load resource: the server responded with a status of 404 ()
manifest.365fbf3a04c65d89e9ef.js:1 Failed to load resource: the server responded with a status of 404 ()
app.214285faf47a78b2002a.js:1 Failed to load resource: the server responded with a status of 404 ()
app.f26ecf43857f2674339ad51c6079b894.css:1 Failed to load resource: the server responded with a status of 404 ()
manifest.365fbf3a04c65d89e9ef.js:1 Failed to load resource: the server responded with a status of 404 ()
vendor.9e961c4bada386773214.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at vendor.9e961c4bada386773214.js:1
app.214285faf47a78b2002a.js:1 Failed to load resource: the server responded with a status of 404 ()
/favicon.ico:1 Failed to load resource: the server responded with a status of 404 ()
app.f26ecf43857f2674339ad51c6079b894.css:1 Failed to load resource: the server responded with a status of 404 ()
```

**Comment by yarikoptic** [comment]
I thought to force push old state but then decided against it since probably there is no rush ATM

**Comment by soichih** [comment]
Oops.. yes, I forgot to commit the ./static after I recompiled it. Sorry
about that. I just pushed it.

**Comment by yarikoptic** [comment]
Use datalad run! :-)

**Comment by yarikoptic** [comment]
Or ideally we could strip compiled stuff and rely on deployment action, may be something of https://github.com/marketplace/actions/deploy-to-github-pages ?

**Pull request merged**
