### PR TITLE
Adds abstract info JSON

### PR DESCRIPTION
**Pull request by rmarkello**
Related to #31, #38, and #44.

I know the JSON is a _bit_ big (tried to minify it to reduce size 🤷‍♂️), but it has (1) all the authors for each poster, (2) the URL to the abstract from AIEvolution (though that's hopefully not necessary anymore), (3) keywords for each poster (a la @nicholst), and (4) a bag of words for each abstract, filtered for words that occur in more than 25% of all abstract.

@yarikoptic @effigies thoughts on adding any or part of this to the search somehow? Don't want to explode the poster.json file but I can edit make_pages.py to integrate stuff as desired!

### CODE REVIEW

**Comment by yarikoptic** [comment]
What about adding a switch (or just two pages) so we could have original (lighter) and heavier (with abstracts)?

**Comment by yarikoptic** [comment]
At JS level it would be just an argument to that `directory` function https://github.com/datalad-datasets/ohbm2020-posters/blob/gh-pages/assets/js/main.js#L439 which would flip between two .json and add one more column to https://github.com/datalad-datasets/ohbm2020-posters/blob/gh-pages/assets/js/main.js#L475 -- although some CSS trick might be desired to make it autoexpanadable or smth

**Comment by rmarkello** [comment]
My JS is no-good very-bad but let me see what I can do!

**Comment by rmarkello** [comment]
Okay so I didn't add abstract info yet—still trying to figure out the best way to make an easily-toggleable switch—but I did add authors + keywords to the datatable (you'll need to re-generate `posters.json` from `make_page.py` for it to work). I didn't make them visible in the table for space constraints but they _are_ searchable. I figure this is still sufficiently lightweight that maybe it's worth moving forwards with this and adding other search (i.e., full abstract info) in a later PR?

**Comment by emdupre** [comment]
I discussed with @rmarkello but just to check -- what are the thoughts about shifting this to a JS framework ? I could quickly replicate it in Vue, for example. Importantly, it would change _where_ the site is served from since GitHub Pages can only handle compiled Vue sites. 

To get around this: one idea is that we could serve it from Netlify and CNAME this site to point to the Netlify app. Then the content would still be hosted here, of course.

**Comment by yarikoptic** [comment]
If someone is willing to do that -- go ahead! could be developed in parallel, until ready. Let me know what needs to be done on our side (any permissions etc) or any service to purchase etc.  Also pay attention to #55 which might soon be completed and merged in to provide a counter for recently joined attendees!

**Comment by rmarkello** [comment]
@yarikoptic : awesome! In the interim, I think this PR is good-to-go on adding authors + keywords. Let me know if you'd like to see anything else!

I'll work with @emdupre on adding abstract info as a toggleable switch on the page in a future PR.

**Comment by yarikoptic** [comment]
It seems something is a bit off -- no keywords  are populated:
```
$> grep keywords posters.json | sort | uniq -c
   2210    "keywords": []
```

**Comment by yarikoptic** [comment]
I tested -- search for an author works!

**Comment by yarikoptic** [comment]
I will fixup for keywords -- I see them present in abstracts.json so it is some minor bug in the script.

**Comment by yarikoptic** [comment]
fixed, merged locally, pushed!  THANKS @rmarkello!

**Comment by yarikoptic** [comment]
Attn @soichih , above comment https://github.com/datalad-datasets/ohbm2020-posters/pull/54#issuecomment-649774556 - reimplementation in Vue might be WIP where you expertise could be of great help. Cheers

**Comment by emdupre** [comment]
I tried to use this as a small hackathon project for myself to test out Vue 3, but it's definitely still in the beta stages (i.e. doesn't yet have Bootstrap-Vue support...).  

I'll roll back to Vue 2.x and look at this again tomorrow. Would be great to collaborate, @soichih !

**Comment by soichih** [comment]
Ahh.. that would make things so much easier (and enjoyable!) if we could use Vue!! @emdupre I'd love to collaborate with you! @yarikoptic Can you merge this? https://github.com/datalad-datasets/ohbm2020-posters/pull/61 The counter might be broken until this gets in.

**Comment by yarikoptic** [comment]
AFAIK everything mergeable was merged

**Pull request merged**
