### PR TITLE
update the cobidas checklist jitsi channel

### PR DESCRIPTION
**Pull request by Remi-Gau**
Not ideal "fix" when people (like me) already have a jitsi channel because if you update the json from parsing the tsv again I will have to make another PR but at least I won't have more than one channel to check.

### CODE REVIEW

**Comment by bpoldrack** [comment]
@Remi-Gau :

How about modifying `make_page.py` instead?
Just insert after https://github.com/datalad-datasets/ohbm2020-posters/blob/0b457cec7c5073272453f0194c62159b5a500a61/tools/make_page.py#L49
a line that checks whether the read-in record is your poster and replace the url entry w/ your hardcoded existing one.

**Comment by yarikoptic** [comment]
ok, the idea for providing "overrides" seems to be most flexible and would allow to change a nicely formatted smaller file.  I will produce a stab of that file in a minute.  But I will need basic JS help to implement such "overrides" at client side at this point: https://github.com/datalad-datasets/ohbm2020-posters/blob/gh-pages/assets/js/main.js#L439 .  But also we would need to adjust invocation there to not just pass a url to the table in `ajax`.

meanwhile, we will make this json multilined for more sensible patching... we will deal with merging changes if regenerated later...

**Comment by yarikoptic** [comment]
@Remi-Gau please just post poster number, URL and may be URL to PDF -- I Am adding overrides functionality now!

**Comment by yarikoptic** [comment]
I failed to quickly review the diff of the one liner ;)

**Comment by Remi-Gau** [comment]
Thanks @bpoldrack and @yarikoptic for the suggestion and looking into this.

**Comment by Remi-Gau** [comment]
> @Remi-Gau please just post poster number, URL and may be URL to PDF -- I Am adding overrides functionality now!

- poster number: 1098
- jitsi url: https://meet.jit.si/cobidas_checklist
- pdf url: https://drive.google.com/file/d/1CirkGPplmrbqilPOq7OdKQJYZzwc0AKc/view?usp=sharing

Would that do?

**Comment by yarikoptic** [comment]
for now -- yes.  later I might want a "pure" downloadable url

**Comment by yarikoptic** [comment]
all done @Remi-Gau : spread the word.  People could send PRs against https://github.com/datalad-datasets/ohbm2020-posters/blob/gh-pages/posters-overrides.json#L3072 like done for yours.  

Also would be great if someone resolve https://github.com/datalad-datasets/ohbm2020-posters/issues/4

**Pull request closed without merging**
